import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { AppService } from 'src/app/app.service';
import { NgForm } from '@angular/forms';
@Component({
  selector: 'app-chat-box',
  templateUrl: './chat-box.component.html',
  styleUrls: ['./chat-box.component.scss'],
})
export class ChatBoxComponent implements OnInit {
  @Output() clicked = new EventEmitter();

  constructor(public app: AppService) {}

  onClick() {
    this.clicked.emit();
  }

  /**
   * this will send the value of the form along with date now.
   * @param form data from chat form.
   */
  onSendChat(form: NgForm) {
    console.log(this.app.room);
    const room = this.app.room;
    form.value.userId = this.app.userID;
    form.value.userName = this.app.userName;
    form.value.date = Date.now();
    room.messages.push(form.value);
    this.app.socket.chat(room);
    form.reset();
  }

  /**
   * this will send name only.
   * id will be generated by the system.
   * @param form sata from user form.
   */
  onSubmitName(form: NgForm) {
    this.app.register(form.value);
    form.reset();
  }

  ngOnInit() {}
}
